# fly.toml app configuration file generated for hello-world-solitary-pond-6059 on 2023-11-24T11:48:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hello-world-solitary-pond-6059"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
