name: Fly Deploy

on:
  workflow_run:
    workflows: ["Check"]
    types: [completed]
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo "Deploying to Fly"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}