name: Test Workflow 2

on:
  workflow_run:
    workflows: ["Test Workflow 1"]
    types: [completed]
  workflow_dispatch:

jobs:
  example-job:
    name: Test job 2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print second stage running
        run: echo "Second stage running"